"""user - add memo

Revision ID: e468bb60b60a
Revises: d53bf62e6c8e
Create Date: 2025-06-11 17:11:29.835940

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e468bb60b60a"
down_revision: Union[str, None] = "d53bf62e6c8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("memo", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("User", "memo")
    # ### end Alembic commands ###
